<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="inspect/**" />
    <EmbeddedResource Remove="inspect/**" />
    <None Remove="inspect/**" />
    <PackageReference Include="Vortice.D3DCompiler" Version="3.8.3" />
    <PackageReference Include="Vortice.Direct3D11" Version="3.8.3" />
    <PackageReference Include="Vortice.DirectComposition" Version="3.8.3" />
    <PackageReference Include="Vortice.DXGI" Version="3.8.3" />
  </ItemGroup>
</Project>
